-- ============================================
-- SIMORA DATABASE SCHEMA
-- ============================================

-- USERS / PROFILES
create table if not exists profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    name text,
    email text unique,
    phone text,
    role text default 'user' check (role in ('user', 'admin')),
    avatar_url text,
    created_at timestamp with time zone default now()
);

-- CATEGORIES
create table if not exists categories (
    id bigint generated by default as identity primary key,
    name text not null,
    image_url text,
    created_at timestamp with time zone default now()
);

-- PRODUCTS
create table if not exists products (
    id bigint generated by default as identity primary key,
    category_id bigint references categories(id) on delete set null,
    name text not null,
    description text,
    price numeric(10,2) not null,
    discount_price numeric(10,2),
    image_url text,
    rating numeric(2,1) default 0,
    stock integer default 0,
    brand text,
    is_active boolean default true,
    created_at timestamp with time zone default now()
);

-- PRODUCT REVIEWS
create table if not exists reviews (
    id bigint generated by default as identity primary key,
    product_id bigint references products(id) on delete cascade,
    user_id uuid references profiles(id) on delete cascade,
    rating integer check (rating between 1 and 5),
    comment text,
    created_at timestamp with time zone default now()
);

-- CART
create table if not exists cart_items (
    id bigint generated by default as identity primary key,
    user_id uuid references profiles(id) on delete cascade,
    product_id bigint references products(id) on delete cascade,
    quantity integer default 1 check (quantity > 0),
    created_at timestamp with time zone default now(),
    unique(user_id, product_id)
);

-- ADDRESSES
create table if not exists addresses (
    id bigint generated by default as identity primary key,
    user_id uuid references profiles(id) on delete cascade,
    name text not null,
    phone text,
    address_line text not null,
    city text,
    state text,
    pincode text,
    is_default boolean default false,
    created_at timestamp with time zone default now()
);

-- ORDERS
create table if not exists orders (
    id bigint generated by default as identity primary key,
    user_id uuid references profiles(id) on delete cascade,
    address_id bigint references addresses(id) on delete set null,
    total_amount numeric(10,2) not null,
    status text default 'pending'
        check (status in (
            'pending',
            'confirmed',
            'packed',
            'shipped',
            'delivered',
            'cancelled'
        )),
    payment_status text default 'pending'
        check (payment_status in ('pending', 'paid', 'failed')),
    created_at timestamp with time zone default now()
);

-- ORDER ITEMS
create table if not exists order_items (
    id bigint generated by default as identity primary key,
    order_id bigint references orders(id) on delete cascade,
    product_id bigint references products(id) on delete set null,
    product_name text,
    price numeric(10,2) not null,
    quantity integer not null check (quantity > 0),
    created_at timestamp with time zone default now()
);

-- WISHLIST
create table if not exists wishlist (
    id bigint generated by default as identity primary key,
    user_id uuid references profiles(id) on delete cascade,
    product_id bigint references products(id) on delete cascade,
    created_at timestamp with time zone default now(),
    unique(user_id, product_id)
);

-- ============================================
-- INDEXES
-- ============================================

create index if not exists products_category_idx
on products(category_id);

create index if not exists cart_user_idx
on cart_items(user_id);

create index if not exists orders_user_idx
on orders(user_id);

create index if not exists reviews_product_idx
on reviews(product_id);

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

alter table profiles enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table reviews enable row level security;
alter table cart_items enable row level security;
alter table addresses enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table wishlist enable row level security;

-- PRODUCTS / CATEGORIES
create policy "Anyone can view categories"
on categories for select
using (true);

create policy "Anyone can view active products"
on products for select
using (is_active = true);

-- REVIEWS
create policy "Anyone can view reviews"
on reviews for select
using (true);

create policy "Users can create reviews"
on reviews for insert
with check (auth.uid() = user_id);

-- PROFILES
create policy "Users can view their profile"
on profiles for select
using (auth.uid() = id);

create policy "Users can update their profile"
on profiles for update
using (auth.uid() = id);

-- CART
create policy "Users can view their cart"
on cart_items for select
using (auth.uid() = user_id);

create policy "Users can add to cart"
on cart_items for insert
with check (auth.uid() = user_id);

create policy "Users can update their cart"
on cart_items for update
using (auth.uid() = user_id);

create policy "Users can delete from cart"
on cart_items for delete
using (auth.uid() = user_id);

-- ADDRESSES
create policy "Users can view their addresses"
on addresses for select
using (auth.uid() = user_id);

create policy "Users can manage their addresses"
on addresses for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- ORDERS
create policy "Users can view their orders"
on orders for select
using (auth.uid() = user_id);

create policy "Users can create orders"
on orders for insert
with check (auth.uid() = user_id);

-- ORDER ITEMS
create policy "Users can view their order items"
on order_items for select
using (
    exists (
        select 1
        from orders
        where orders.id = order_items.order_id
        and orders.user_id = auth.uid()
    )
);

-- WISHLIST
create policy "Users can view their wishlist"
on wishlist for select
using (auth.uid() = user_id);

create policy "Users can add to wishlist"
on wishlist for insert
with check (auth.uid() = user_id);

create policy "Users can remove from wishlist"
on wishlist for delete
using (auth.uid() = user_id);